### ISSUE TITLE
1.20.1: no member named `starts_with`

### ISSUE THREAD

**Issue by 0-wiz-0** [strukturag/libheif#1548]
When updating the pkgsrc package from 1.19.8 to 1.20.1 I see a new error:
```
/scratch/graphics/libheif/work/.cwrapper/bin/c++ -DENABLE_MULTITHREADING_SUPPORT=1 -DENABLE_PARALLEL_TILE_DECODING=1 -DENABLE_PLUGIN_LOADING=1 -DHAVE_AOM_DECODER=1 -DHAVE_AOM_ENCODER=1 -DHAVE_LIBDE265=1 -DHAVE_OpenH264_D
ECODER=1 -DHAVE_UNISTD_H -DHAVE_VISIBILITY -DHAVE_X265=1 -DIS_BIG_ENDIAN=0 -DLIBHEIF_EXPORTS -Dheif_EXPORTS -I/scratch/graphics/libheif/work/libheif-1.20.1/cmake-pkgsrc-build -I/scratch/graphics/libheif/work/libheif-1.20
.1/libheif -I/scratch/graphics/libheif/work/libheif-1.20.1/libheif/api -I/scratch/graphics/libheif/work/libheif-1.20.1/include/libheif -I/scratch/graphics/libheif/work/libheif-1.20.1/include -O2 -g -fstack-clash-protecti
on -I/usr/pkg/include -I/usr/include -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=
deprecated-declarations -MD -MT libheif/CMakeFiles/heif.dir/error.cc.o -MF libheif/CMakeFiles/heif.dir/error.cc.o.d -o libheif/CMakeFiles/heif.dir/error.cc.o -c /scratch/graphics/libheif/work/libheif-1.20.1/libheif/error
.cc
/scratch/graphics/libheif/work/libheif-1.20.1/libheif/error.cc: In static member function 'static Error Error::from_heif_error(const heif_error&)':
/scratch/graphics/libheif/work/libheif-1.20.1/libheif/error.cc:59:11: error: 'std::string' {aka 'class std::__cxx11::basic_string<char>'} has no member named 'starts_with'
   59 |   if (msg.starts_with(err_string)) {
      |           ^~~~~~~~~~~
/scratch/graphics/libheif/work/libheif-1.20.1/libheif/error.cc:62:13: error: 'std::string' {aka 'class std::__cxx11::basic_string<char>'} has no member named 'starts_with'
   62 |     if (msg.starts_with(": ")) {
      |             ^~~~~~~~~~~
/scratch/graphics/libheif/work/libheif-1.20.1/libheif/error.cc:66:13: error: 'std::string' {aka 'class std::__cxx11::basic_string<char>'} has no member named 'starts_with'
   66 |     if (msg.starts_with(sub_err_string)) {
      |             ^~~~~~~~~~~
/scratch/graphics/libheif/work/libheif-1.20.1/libheif/error.cc:69:15: error: 'std::string' {aka 'class std::__cxx11::basic_string<char>'} has no member named 'starts_with'
   69 |       if (msg.starts_with(": ")) {
      |               ^~~~~~~~~~~
```

That's with gcc 12.4.0 on NetBSD 10.99.14/x86_64 in case it matters, but I think it's because this is compiled with `-std=c++17` but uses a C++20 feature, according to https://en.cppreference.com/w/cpp/string/basic_string/starts_with

**Comment by farindk** [comment]
Thank you. Fixed in the above commit. Do you need a new release?

**Comment by 0-wiz-0** [comment]
Thank you for the quick fix! No need, I'll add the patch to pkgsrc manually.
