### ISSUE TITLE
Error compiling with gcc 4.9.3

### ISSUE THREAD

**Issue by jeroen** [strukturag/libheif#421]
Compiling with gcc-4.9.3 (mingw-w64) fails with:

```
./../libheif-1.10.0/libheif/heif_colorconversion.cc: In member function 'virtual std::shared_ptr<heif::HeifPixelImage> Op_RGB24_32_to_YCbCr::convert_colorspace(const std::shared_ptr<const heif::HeifPixelImage>&, heif::ColorState, heif::ColorConversionOptions)':
../../libheif-1.10.0/libheif/heif_colorconversion.cc:2037:35: error: 'out_a' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         out_a[y * out_a_stride + x] = a;
                                   ^
```

Full log: https://github.com/r-windows/rtools-backports/pull/35/checks?check_run_id=1691955338

Should I just ignore this and remove the `-Werror` from CMakeLists.txt ?

**Comment by silverbacknet** [comment]
4.9.3 is ancient. I don't get that warning on 10, maybe upgrade? http://winlibs.com/

If you have to stick to 4.9, consolidating the line above `out_a = outimg->get_plane(heif_channel_Alpha, &out_a_stride);` into the if would fix it, the warning checker in that version must not be smart enough to suss out that both branches have the exact same condition.

**Comment by jeroen** [comment]
Yes I already have a successful build with 8.3.0 but I also need a binary that is compatible with 4.9.3 for an older stack.

It's not important I'll just remove the `-Werror` from the configure.

**Comment by farindk** [comment]
Made a change that should fix the warning.
