### ISSUE TITLE
symbol lookup error in codec plugin

### ISSUE THREAD

**Issue by chunronglai** [strukturag/libheif#745]
hi, colleagues:

   As the attached picture shows, I met error when run simple command line as "./heif-enc -A -e rav1e -q 45 ./lake-3000.jpg -o dst2.avif".
   The error info are  "symbol lookup error: ..../libheif-rav1e.so: undefined symbol: _ZNK4heif14HeifPixelImage18get_bits_per_pixelE12heif_channel".
   I also checked it with objdump and does see the symbol in libheif.so instead of in the plugin.
    Anything I should notice or improve during the library build or example run? Thanks a lot.

<img width="656" alt="symbol lookup error" src="https://user-images.githubusercontent.com/80802212/208628216-bf831d52-18ec-43f3-a644-2ab7c96a2548.png">

**Comment by chunronglai** [comment]
I think the error come from some configurations of the plugin building. 
Anyway, the symbol lookup error disappear with below patch:
--- a/libheif/plugins/heif_encoder_rav1e.cc
+++ b/libheif/plugins/heif_encoder_rav1e.cc
@@ -522,7 +522,8 @@ struct heif_error rav1e_encode_image(void* encoder_raw, const struct heif_image*
     rav1eRange = nclx->get_full_range_flag() ? RA_PIXEL_RANGE_FULL : RA_PIXEL_RANGE_LIMITED;
   }

-  int bitDepth = image->image->get_bits_per_pixel(heif_channel_Y);
+  int bitDepth = heif_image_get_bits_per_pixel_range(image, heif_channel_Y);

@@ -607,11 +608,14 @@ struct heif_error rav1e_encode_image(void* encoder_raw, const struct heif_image*
   //} else
   {
     int strideY;
-    const uint8_t* Y = image->image->get_plane(heif_channel_Y, &strideY);
+    const uint8_t* Y = heif_image_get_plane_readonly(image, heif_channel_Y, &strideY);
     int strideCb;
-    const uint8_t* Cb = image->image->get_plane(heif_channel_Cb, &strideCb);
+    const uint8_t* Cb = heif_image_get_plane_readonly(image, heif_channel_Cb, &strideCb);
     int strideCr;
-    const uint8_t* Cr = image->image->get_plane(heif_channel_Cr, &strideCr);
+    const uint8_t* Cr = heif_image_get_plane_readonly(image, heif_channel_Cr, &strideCr);

Say, when the error happens, the application try to find the implementation of image->image->XXX() from the plugin instead of libheif.so, where the functions are implemented, for example, in libheif/libheif_image.cc

**Comment by scaronni** [comment]
This is actually happening with all plugins:
```
$ heif-enc --list encoders 
dlopen: /usr/lib64/libheif/libheif-aomenc.so: undefined symbol: _ZN4heif20chroma_h_subsamplingE11heif_chroma
dlopen: /usr/lib64/libheif/libheif-dav1d.so: undefined symbol: _ZN4heif19get_subsampled_sizeEii12heif_channel11heif_chromaPiS2_
dlopen: /usr/lib64/libheif/libheif-rav1e.so: undefined symbol: _ZNK4heif14HeifPixelImage18get_bits_per_pixelE12heif_channel
dlopen: /usr/lib64/libheif/libheif-svtenc.so: undefined symbol: _ZN4heif14HeifPixelImage22extend_padding_to_sizeEii
dlopen: /usr/lib64/libheif/libheif-x265.so: undefined symbol: _ZN4heif14HeifPixelImage22extend_padding_to_sizeEii
Encoders (first is default):
```

**Comment by scaronni** [comment]
Except `libheif-libde265.so`.

**Comment by scaronni** [comment]
Could you please format correctly the patch at https://github.com/strukturag/libheif/issues/745#issuecomment-1378446107 so we can have a look? Thanks.

**Comment by arjendekorte** [comment]
I see the same behavior on openSUSE Tumbleweed, which by default is linked with `-z now` nowadays. Switching this off with `export SUSE_ZNOW=0` fixes this and there are no more symbol lookup errors. Alternatively, disabling the dynamic plugin interface with `-DENABLE_PLUGIN_LOADING=OFF` also works around the problem.

Note that the mentioned patch is not a complete fix (at least not when linking with `-z now`). It changes the symbol lookup error and fails to find `heif_image_get_plane_readonly` instead.

**Comment by arjendekorte** [comment]
I checked out the master version and this seems to have fixed the missing symbols

**Comment by farindk** [comment]
@arjendekorte Thanks for checking.

**Comment by scaronni** [comment]
I'm getting an error when building the SVT plugin:
```
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc: In function 'heif_error svt_encode_image(void*, const heif_image*, heif_image_input_class)':
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc:657:61: error: 'struct heif_color_profile_nclx' has no member named 'get_colour_primaries'; did you mean 'color_primaries'?
  657 |     svt_config.color_primaries = static_cast<uint8_t>(nclx->get_colour_primaries());
      |                                                             ^~~~~~~~~~~~~~~~~~~~
      |                                                             color_primaries
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc:658:70: error: 'struct heif_color_profile_nclx' has no member named 'get_transfer_characteristics'; did you mean 'transfer_characteristics'?
  658 |     svt_config.transfer_characteristics = static_cast<uint8_t>(nclx->get_transfer_characteristics());
      |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                      transfer_characteristics
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc:659:65: error: 'struct heif_color_profile_nclx' has no member named 'get_matrix_coefficients'; did you mean 'matrix_coefficients'?
  659 |     svt_config.matrix_coefficients = static_cast<uint8_t>(nclx->get_matrix_coefficients());
      |                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                                 matrix_coefficients
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc:660:36: error: 'struct heif_color_profile_nclx' has no member named 'get_full_range_flag'; did you mean 'full_range_flag'?
  660 |     svt_config.color_range = nclx->get_full_range_flag() ? 1 : 0;
      |                                    ^~~~~~~~~~~~~~~~~~~
      |                                    full_range_flag
```
Is there a minimum SVT version required?

**Comment by arjendekorte** [comment]
> Is there a minimum SVT version required?

Works just fine here:
```
# heif-enc --list encoders
AVIF encoders:
- aom = AOMedia Project AV1 Encoder v3.5.0 [default]
- svt = SVT-AV1 encoder v1.4.1
- rav1e = Rav1e encoder
HEIC encoders:
- x265 = x265 HEVC encoder (3.5~+87~git20230120.6da609e41) [default]
```

**Comment by farindk** [comment]
@scaronni Thanks, there was another one hiding behind an `#if` that was only active for old SVT versions. I've corrected that now.

**Comment by scaronni** [comment]
Just to be clear, I'm building it on multiple Red Hat based distributions, so the libraries are different on each. Now it builds with SVT-AV1 1.1.0 but not anymore with SVT-AV1 0.9.1.
```
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc: In function 'heif_error svt_encode_image(void*, const heif_image*, heif_image_input_class)':
/builddir/build/BUILD/libheif-96a114f7e1e49d1a6f07dea0f249d260fb5d4294/libheif/plugins/heif_encoder_svt.cc:657:61: error: 'struct heif_color_profile_nclx' has no member named 'colour_primaries'; did you mean 'color_primaries'?
```

**Comment by farindk** [comment]
@scaronni Typo should be fixed now.

**Comment by scaronni** [comment]
Many thanks, it all works now!
