### ISSUE TITLE
1.20.0 fails to build on Windows

### ISSUE THREAD

**Issue by lazka** [strukturag/libheif#1542]
```
  FAILED: [code=1] libheif/CMakeFiles/heif.dir/plugins/decoder_openjpeg.cc.obj 
  D:\M\msys64\clang64\bin\clang++.exe -DENABLE_MULTITHREADING_SUPPORT=1 -DENABLE_PARALLEL_TILE_DECODING=1 -DHAVE_AOM_DECODER=1 -DHAVE_AOM_ENCODER=1 -DHAVE_BROTLI=1 -DHAVE_DAV1D=1 -DHAVE_JPEG_DECODER=1 -DHAVE_JPEG_ENCODER=1 -DHAVE_KVAZAAR=1 -DHAVE_KVAZAAR_ENABLE_LOGGING=1 -DHAVE_LIBDE265=1 -DHAVE_LIBSHARPYUV=1 -DHAVE_OPENJPEG_DECODER=1 -DHAVE_OPENJPEG_ENCODER=1 -DHAVE_OPENJPH_ENCODER=1 -DHAVE_OpenH264_DECODER=1 -DHAVE_RAV1E=1 -DHAVE_SvtEnc=1 -DHAVE_UNISTD_H -DHAVE_VISIBILITY -DHAVE_X265=1 -DHAVE_ZLIB=1 -DIS_BIG_ENDIAN=0 -DLIBHEIF_EXPORTS -Dheif_EXPORTS -ID:/_/B/src/build-CLANG64 -ID:/_/B/src/libheif-1.20.0/libheif -ID:/_/B/src/libheif-1.20.0/libheif/api -ID:/_/B/src/libheif-1.20.0/include/libheif -ID:/_/B/src/libheif-1.20.0/include -ID:/M/msys64/clang64/include/rav1e -ID:/M/msys64/clang64/include/webp -isystem D:/M/msys64/clang64/include/openjpeg-2.5 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -O3 -DNDEBUG -std=c++20 -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -Wno-error=unused-parameter -Wno-error=deprecated-declarations -Wno-error=tautological-compare -Wno-error=tautological-constant-out-of-range-compare -Wno-error=potentially-evaluated-expression -MD -MT libheif/CMakeFiles/heif.dir/plugins/decoder_openjpeg.cc.obj -MF libheif\CMakeFiles\heif.dir\plugins\decoder_openjpeg.cc.obj.d -o libheif/CMakeFiles/heif.dir/plugins/decoder_openjpeg.cc.obj -c D:/_/B/src/libheif-1.20.0/libheif/plugins/decoder_openjpeg.cc
  D:/_/B/src/libheif-1.20.0/libheif/plugins/decoder_openjpeg.cc:32:10: fatal error: 'err.h' file not found
     32 | #include <err.h>
```

Introduced in 5fe3a6d43f2f766236

**Comment by farindk** [comment]
No idea why that include is there. Maybe my IDE inserted that and it slipped through...
Can you patch that out on your side until the next release?

**Comment by lazka** [comment]
sure, no prob

**Comment by farindk** [comment]
Good. Thanks for the report.

**Comment by farindk** [comment]
I had to do a quick v1.20.1 patch release because of another bug. That version also includes the above patch.

**Comment by lazka** [comment]
All good now with 1.20.1, thanks!
