### ISSUE TITLE
Build with SVT-AV1 v4.1.0 fails

### ISSUE THREAD

**Issue by dloebl** [strukturag/libheif#1741]
```
/app/vendor/libheif-1.21.2/libheif/plugins/encoder_svt.cc: In function 'heif_error svt_start_sequence_encoding_intern(void*, const heif_image*, heif_image_input_class, uint32_t, uint32_t, const heif_sequence_encoding_options*, bool)':
--
/app/vendor/libheif-1.21.2/libheif/plugins/encoder_svt.cc:851:37: error: 'SvtAv1PredStructure' has not been declared
851 \|         svt_config.pred_structure = SvtAv1PredStructure::SVT_AV1_PRED_RANDOM_ACCESS;
\|                                     ^~~~~~~~~~~~~~~~~~~
make[2]: *** [libheif/CMakeFiles/heif.dir/build.make:1336: libheif/CMakeFiles/heif.dir/plugins/encoder_svt.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1358: libheif/CMakeFiles/heif.dir/all] Error 2
```

**libheif version:** v1.21.2

**Comment by kmilos** [comment]
Known issue: https://github.com/strukturag/libheif/pull/1680#issuecomment-4116807448

**Comment by fancycode** [comment]
Fixed by #1680.
