### ISSUE TITLE
Build failure when compiling against libjpeg-turbo 2.0

### ISSUE THREAD

**Issue by hmage** [strukturag/libheif#70]
After upgrading from libjpeg-turbo 1.5.3 to 2.0.0 from https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.0, libheif fails to build:

```
(min) hmage@min:~/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz$ make
make  all-recursive
make[1]: Entering directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz'
Making all in libheif
make[2]: Entering directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz/libheif'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz/libheif'
Making all in examples
make[2]: Entering directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz/examples'
c++ -DHAVE_CONFIG_H -I. -I..   -I/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/include -march=native -fdebug-prefix-map=/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min=/build -ffunction-sections -fdata-sections -I.. -I../.   -g -O2 -Wall -Werror -Wsign-compare -Wconversion -Wno-sign-conversion -Wno-error=conversion -c -o heif_convert-heif_convert.o `test -f 'heif_convert.cc' || echo './'`heif_convert.cc
In file included from /home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/include/jpeglib.h:29:0,
                 from encoder_jpeg.h:27,
                 from heif_convert.cc:38:
/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/include/jconfig.h:39:0: error: "HAVE_STDDEF_H" redefined [-Werror]
 #define HAVE_STDDEF_H

In file included from heif_convert.cc:21:0:
../config.h:38:0: note: this is the location of the previous definition
 #define HAVE_STDDEF_H 1

In file included from /home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/include/jpeglib.h:29:0,
                 from encoder_jpeg.h:27,
                 from heif_convert.cc:38:
/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/include/jconfig.h:42:0: error: "HAVE_STDLIB_H" redefined [-Werror]
 #define HAVE_STDLIB_H

In file included from heif_convert.cc:21:0:
../config.h:44:0: note: this is the location of the previous definition
 #define HAVE_STDLIB_H 1

cc1plus: all warnings being treated as errors
Makefile:662: recipe for target 'heif_convert-heif_convert.o' failed
make[2]: *** [heif_convert-heif_convert.o] Error 1
make[2]: Leaving directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz/examples'
Makefile:507: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hmage/norm.x86_64-pc-linux-gnu.2.24.haswell.min/tmp/compile/libheif/libheif_libheif-1.3.2.tar.gz'
Makefile:416: recipe for target 'all' failed
make: *** [all] Error 2
```

Didn't have time yet to track down exactly why, but better have the bugreport rather than not.

**Comment by farindk** [comment]
Thanks. While we may be able to provide a workaround, I think this feels more like a jpegturbo issue. I consider it bad practice that they include their configuration defines in the public API files.

**Comment by Whissi** [comment]
Another one with libjpeg-turbo-2.0 but GCC 8.2 on Gentoo:
```
/var/tmp/portage/media-libs/libheif-9999/work/libheif-9999/examples/encoder_jpeg.cc:64:6: error: ‘void jpeg_write_icc_profile(j_compress_ptr, const JOCTET*, unsigned int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 void jpeg_write_icc_profile(j_compress_ptr cinfo, const JOCTET *icc_data_ptr,
      ^~~~~~~~~~~~~~~~~~~~~~
In file included from /var/tmp/portage/media-libs/libheif-9999/work/libheif-9999/examples/encoder_jpeg.h:27,
                 from /var/tmp/portage/media-libs/libheif-9999/work/libheif-9999/examples/encoder_jpeg.cc:26:
/usr/include/jpeglib.h:979:14: note: previous declaration of ‘void jpeg_write_icc_profile(j_compress_ptr, const JOCTET*, unsigned int)’
 EXTERN(void) jpeg_write_icc_profile(j_compress_ptr cinfo,
              ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:693: heif_convert-encoder_jpeg.o] Error 1
```

**Comment by farindk** [comment]
The redefinition of the autoconf macros has been fixed in libjpeg-turbo in release v2.0.1:
  https://github.com/libjpeg-turbo/libjpeg-turbo/issues/280

I do not consider this a libheif problem, but we may add the workaround as a temporary solution.
